# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import json
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_LoginPage(QWidget):
    def __init__(self, layers,socket):
        super().__init__()
        self.layers = layers
        self.socket = socket
        self.id = ""
        self.password = ""
        self.setupUi()
    
    def set_id(self, value):
        self.id = value
    
    def set_password(self, value):
        self.password = value
    
    def setupUi(self):
        self.setObjectName("LoginPage")
        self.resize(480, 640)
        self.setMinimumSize(QSize(480, 640))
        
        self.MainLayout = QVBoxLayout(self)
        self.MainLayout.setObjectName("MainLayout")
        MainLayoutSpacerTop = QSpacerItem(20, 215, QSizePolicy.Minimum,
                                          QSizePolicy.Expanding)
        self.MainLayout.addItem(MainLayoutSpacerTop)
        
        self.ContentsLayout = QHBoxLayout()
        self.ContentsLayout.setObjectName("ContentsLayout")
        ContentsLayoutSpacerLeft = QSpacerItem(40, 20, QSizePolicy.Expanding,
                                               QSizePolicy.Minimum)
        self.ContentsLayout.addItem(ContentsLayoutSpacerLeft)
        
        self.LoginFormLayout = QVBoxLayout()
        self.LoginFormLayout.setObjectName("LoginFormLayout")
        
        self.LineEditLayout = QVBoxLayout()
        self.LineEditLayout.setSpacing(0)
        self.LineEditLayout.setObjectName("LineEditLayout")
        # line_edit_id
        self.id_line_edit = QLineEdit(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_line_edit.sizePolicy().hasHeightForWidth())
        self.id_line_edit.setSizePolicy(sizePolicy)
        self.id_line_edit.setMinimumSize(QSize(270, 40))
        self.id_line_edit.setObjectName("id_lineEdit")
        self.LineEditLayout.addWidget(self.id_line_edit, 0, Qt.AlignHCenter)
        self.id_line_edit.textChanged.connect(lambda v: self.set_id(v))
        
        # line_edit_password
        self.password_line_edit = QLineEdit(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_line_edit.sizePolicy().hasHeightForWidth())
        self.password_line_edit.setSizePolicy(sizePolicy)
        self.password_line_edit.setMinimumSize(QSize(270, 40))
        self.password_line_edit.setEchoMode(QLineEdit.Password)
        self.password_line_edit.setObjectName("password_lineEdit")
        self.password_line_edit.textChanged.connect(lambda v: self.set_password(v))
        
        self.LineEditLayout.addWidget(self.password_line_edit, 0, Qt.AlignHCenter)
        self.LineEditLayout.setStretch(0, 1)
        self.LineEditLayout.setStretch(1, 1)
        self.LoginFormLayout.addLayout(self.LineEditLayout)
        
        self.ButtonLayout = QHBoxLayout()
        self.ButtonLayout.setSpacing(6)
        self.ButtonLayout.setObjectName("ButtonLayout")
        # signup_button
        self.signup_button = QPushButton(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_button.sizePolicy().hasHeightForWidth())
        self.signup_button.setSizePolicy(sizePolicy)
        self.signup_button.setMinimumSize(QSize(133, 35))
        self.signup_button.setObjectName("signup_button")
        self.ButtonLayout.addWidget(self.signup_button)
        self.signup_button.clicked.connect(self.click_signup)
        # login_button
        self.login_button = QPushButton(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setMinimumSize(QSize(133, 35))
        self.login_button.setObjectName("login_button")
        self.login_button.clicked.connect(self.click_login)
        
        self.ButtonLayout.addWidget(self.login_button)
        self.ButtonLayout.setStretch(0, 1)
        self.ButtonLayout.setStretch(1, 1)
        self.LoginFormLayout.addLayout(self.ButtonLayout)
        self.LoginFormLayout.setStretch(0, 2)
        self.LoginFormLayout.setStretch(1, 1)
        self.ContentsLayout.addLayout(self.LoginFormLayout)
        
        ContentsLayoutSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding,
                                           QSizePolicy.Minimum)
        self.ContentsLayout.addItem(ContentsLayoutSpacer)
        self.ContentsLayout.setStretch(0, 1)
        self.ContentsLayout.setStretch(1, 3)
        self.ContentsLayout.setStretch(2, 1)
        
        self.MainLayout.addLayout(self.ContentsLayout)
        MainLayoutSpacerBottom = QSpacerItem(20, 215, QSizePolicy.Minimum,
                                             QSizePolicy.Expanding)
        self.MainLayout.addItem(MainLayoutSpacerBottom)
        self.MainLayout.setStretch(0, 5)
        self.MainLayout.setStretch(1, 4)
        self.MainLayout.setStretch(2, 5)
        
        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)
    
    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate("LoginPage", "Form"))
        self.id_line_edit.setPlaceholderText(_translate("LoginPage", "로그인"))
        self.password_line_edit.setPlaceholderText(_translate("LoginPage", "비밀번호"))
        self.signup_button.setText(_translate("LoginPage", "회원가입"))
        self.login_button.setText(_translate("LoginPage", "로그인"))
    
    def click_login(self):
        print("버튼 클릭")
        print("id:", self.id, " password:", self.password)
        print(self.id and self.password)
        if not self.id or not self.password:
            print("test")
            QMessageBox.about(self, "title", "아이디와 비밀번호를 입력해주세요")
            return
        payload_data = {
            "request": "login",
            "params": {
                "id": self.id,
                "password": self.password
            }
        }
        payload = json.dumps(payload_data)
        print(payload)
        self.socket.send(payload)
    
    def click_signup(self):
        self.layers.setCurrentIndex(1)


if __name__ == "__main__":
    import sys
    
    app = QApplication(sys.argv)
    LoginPage = QWidget()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
