# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(480, 640)
        LoginPage.setMinimumSize(QtCore.QSize(480, 640))
       
        self.MainLayout = QtWidgets.QVBoxLayout(LoginPage)
        self.MainLayout.setObjectName("MainLayout")
        MainLayoutSpacerTop = QtWidgets.QSpacerItem(20, 215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.MainLayout.addItem(MainLayoutSpacerTop)
        
        self.ContentsLayout = QtWidgets.QHBoxLayout()
        self.ContentsLayout.setObjectName("ContentsLayout")
        ContentsLayoutSpacerLeft = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ContentsLayout.addItem(ContentsLayoutSpacerLeft)
        
        self.LoginFormLayout = QtWidgets.QVBoxLayout()
        self.LoginFormLayout.setObjectName("LoginFormLayout")
        
        self.LineEditLayout = QtWidgets.QVBoxLayout()
        self.LineEditLayout.setSpacing(0)
        self.LineEditLayout.setObjectName("LineEditLayout")
        
        self.id_lineEdit = QtWidgets.QLineEdit(LoginPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_lineEdit.sizePolicy().hasHeightForWidth())
        self.id_lineEdit.setSizePolicy(sizePolicy)
        self.id_lineEdit.setMinimumSize(QtCore.QSize(270, 40))
        self.id_lineEdit.setObjectName("id_lineEdit")
        self.LineEditLayout.addWidget(self.id_lineEdit, 0, QtCore.Qt.AlignHCenter)
        
        self.password_lineEdit = QtWidgets.QLineEdit(LoginPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_lineEdit.sizePolicy().hasHeightForWidth())
        self.password_lineEdit.setSizePolicy(sizePolicy)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(270, 40))
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        
        self.LineEditLayout.addWidget(self.password_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.LineEditLayout.setStretch(0, 1)
        self.LineEditLayout.setStretch(1, 1)
        self.LoginFormLayout.addLayout(self.LineEditLayout)
        
        self.ButtonLayout = QtWidgets.QHBoxLayout()
        self.ButtonLayout.setSpacing(6)
        self.ButtonLayout.setObjectName("ButtonLayout")
        
        self.signup_button = QtWidgets.QPushButton(LoginPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_button.sizePolicy().hasHeightForWidth())
        self.signup_button.setSizePolicy(sizePolicy)
        self.signup_button.setMinimumSize(QtCore.QSize(133, 35))
        self.signup_button.setObjectName("signup_button")
        self.ButtonLayout.addWidget(self.signup_button)
        
        self.login_button = QtWidgets.QPushButton(LoginPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setMinimumSize(QtCore.QSize(133, 35))
        self.login_button.setObjectName("login_button")
        
        self.ButtonLayout.addWidget(self.login_button)
        self.ButtonLayout.setStretch(0, 1)
        self.ButtonLayout.setStretch(1, 1)
        self.LoginFormLayout.addLayout(self.ButtonLayout)
        self.LoginFormLayout.setStretch(0, 2)
        self.LoginFormLayout.setStretch(1, 1)
        self.ContentsLayout.addLayout(self.LoginFormLayout)
        
        ContentsLayoutSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ContentsLayout.addItem(ContentsLayoutSpacer)
        self.ContentsLayout.setStretch(0, 1)
        self.ContentsLayout.setStretch(1, 3)
        self.ContentsLayout.setStretch(2, 1)
        
        self.MainLayout.addLayout(self.ContentsLayout)
        MainLayoutSpacerBottom = QtWidgets.QSpacerItem(20, 215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.MainLayout.addItem(MainLayoutSpacerBottom)
        self.MainLayout.setStretch(0, 5)
        self.MainLayout.setStretch(1, 4)
        self.MainLayout.setStretch(2, 5)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Form"))
        self.id_lineEdit.setPlaceholderText(_translate("LoginPage", "로그인"))
        self.password_lineEdit.setPlaceholderText(_translate("LoginPage", "비밀번호"))
        self.signup_button.setText(_translate("LoginPage", "회원가입"))
        self.login_button.setText(_translate("LoginPage", "로그인"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QWidget()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
